"""initial_schema_reset

Revision ID: 0f22f0f204f2
Revises:
Create Date: 2026-01-05 12:48:22.850533

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0f22f0f204f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
