"""add_movies_and_genres

Revision ID: 1e3d903a0919
Revises: 2204640c5611
Create Date: 2026-01-03 17:14:34.317051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e3d903a0919"
down_revision: Union[str, Sequence[str], None] = "2204640c5611"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genres_id"), "genres", ["id"], unique=False)
    op.create_index(op.f("ix_genres_name"), "genres", ["name"], unique=True)
    op.create_table(
        "movie_genres",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "genre_id"),
    )
    op.add_column("movies", sa.Column("video_url", sa.String(), nullable=False))
    op.add_column("movies", sa.Column("thumbnail_url", sa.String(), nullable=False))
    op.add_column("movies", sa.Column("release_year", sa.Integer(), nullable=False))
    op.add_column("movies", sa.Column("is_published", sa.Boolean(), nullable=False))
    op.alter_column("movies", "description", existing_type=sa.TEXT(), nullable=False)
    op.drop_constraint(op.f("movies_user_id_fkey"), "movies", type_="foreignkey")
    op.drop_column("movies", "director")
    op.drop_column("movies", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "movies",
        sa.Column("director", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("movies_user_id_fkey"), "movies", "users", ["user_id"], ["id"]
    )
    op.alter_column("movies", "description", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("movies", "is_published")
    op.drop_column("movies", "release_year")
    op.drop_column("movies", "thumbnail_url")
    op.drop_column("movies", "video_url")
    op.drop_table("movie_genres")
    op.drop_index(op.f("ix_genres_name"), table_name="genres")
    op.drop_index(op.f("ix_genres_id"), table_name="genres")
    op.drop_table("genres")
    # ### end Alembic commands ###
