"""add_notifications_table

Revision ID: 2d030c1bc1ec
Revises: 82424c55b249
Create Date: 2026-01-04 15:58:27.460195

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "2d030c1bc1ec"
down_revision: Union[str, Sequence[str], None] = "82424c55b249"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
