"""Add watchlist table

Revision ID: 415803143e8d
Revises: bc8ad337ce65
Create Date: 2026-01-01 16:04:27.195407

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "415803143e8d"
down_revision: Union[str, Sequence[str], None] = "bc8ad337ce65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
