"""add_link_movie_ratings

Revision ID: 527662db6d31
Revises: 7cc28e3e836e
Create Date: 2026-01-03 17:39:03.822963

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "527662db6d31"
down_revision: Union[str, Sequence[str], None] = "7cc28e3e836e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
