"""add_notifications_table

Revision ID: 82424c55b249
Revises: a40a588de1b2
Create Date: 2026-01-04 15:51:17.092995

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "82424c55b249"
down_revision: Union[str, Sequence[str], None] = "a40a588de1b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
