"""add_vector_extension_and_column

Revision ID: 8aa6c14e277c
Revises: 2528e1693235
Create Date: 2026-01-07 13:38:18.092710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "8aa6c14e277c"
down_revision: Union[str, Sequence[str], None] = "2528e1693235"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column("movies", sa.Column("embedding", Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "embedding")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
