"""add_link_movie_ratings

Revision ID: 90a164b1d36b
Revises: 527662db6d31
Create Date: 2026-01-03 17:40:42.630102

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "90a164b1d36b"
down_revision: Union[str, Sequence[str], None] = "527662db6d31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
