"""optimization_day_59

Revision ID: a40a588de1b2
Revises: dfc7c5e93abe
Create Date: 2026-01-03 18:30:28.143502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a40a588de1b2"
down_revision: Union[str, Sequence[str], None] = "dfc7c5e93abe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("genres", sa.Column("slug", sa.String(), nullable=True))
    op.execute("UPDATE genres SET slug = lower(replace(name, ' ', '-'))")
    op.alter_column("genres", "slug", nullable=False)
    op.execute("DROP INDEX IF EXISTS ix_genres_slug")
    op.create_index(op.f("ix_genres_slug"), "genres", ["slug"], unique=True)
    op.add_column("movies", sa.Column("slug", sa.String(), nullable=True))
    op.execute("UPDATE movies SET slug = lower(replace(title, ' ', '-'))")
    op.alter_column("movies", "slug", nullable=False)
    op.execute("DROP INDEX IF EXISTS ix_movies_slug")
    op.create_index(op.f("ix_movies_slug"), "movies", ["slug"], unique=True)
    op.add_column(
        "movies",
        sa.Column("average_rating", sa.Float(), nullable=False, server_default="0"),
    )
    op.add_column(
        "movies",
        sa.Column("rating_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("movies", "average_rating", server_default=None)
    op.alter_column("movies", "rating_count", server_default=None)

    op.execute("DROP INDEX IF EXISTS ix_movies_average_rating")
    op.create_index(
        op.f("ix_movies_average_rating"), "movies", ["average_rating"], unique=False
    )
    op.add_column(
        "movies",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', title || ' ' || description)", persisted=True
            ),
            nullable=True,
        ),
    )

    op.execute("DROP INDEX IF EXISTS ix_movies_search_vector")
    op.create_index(
        "ix_movies_search_vector",
        "movies",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )

    op.add_column(
        "movies",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "movies",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.add_column(
        "ratings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "ratings",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("users", "deleted_at")
    op.drop_column("ratings", "updated_at")
    op.drop_column("ratings", "created_at")
    op.drop_index(op.f("ix_movies_slug"), table_name="movies")
    op.drop_index(
        "ix_movies_search_vector", table_name="movies", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_movies_average_rating"), table_name="movies")
    op.drop_column("movies", "updated_at")
    op.drop_column("movies", "created_at")
    op.drop_column("movies", "search_vector")
    op.drop_column("movies", "rating_count")
    op.drop_column("movies", "average_rating")
    op.drop_column("movies", "slug")
    op.drop_index(op.f("ix_genres_slug"), table_name="genres")
    op.drop_column("genres", "slug")
    # ### end Alembic commands ###
