"""reset_database

Revision ID: bad6ecde55e2
Revises: 0f22f0f204f2
Create Date: 2026-01-05 12:50:24.384595

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bad6ecde55e2"
down_revision: Union[str, Sequence[str], None] = "0f22f0f204f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
