"""add_notifications_table

Revision ID: c2933bd58b06
Revises: 60ba069d3e2f
Create Date: 2026-01-04 16:42:16.399544

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c2933bd58b06"
down_revision: Union[str, Sequence[str], None] = "60ba069d3e2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
